### ISSUE TITLE
Add action-misspell

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/action-dotenv-linter#16]
Add `action-misspell` to correct commonly misspelled English words in source files.

Link:
https://github.com/reviewdog/action-misspell

**Comment by vvkpd** [comment]
I want to own it up, please assign to me

**Comment by vvkpd** [comment]
@mgrachev One question, which locale we should use US/UK?

**Comment by mgrachev** [comment]
> @mgrachev One question, which locale we should use US/UK?

US.
